---
title: "Viz Part 1"
author: "Zilin Huang"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(ggridges)
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_df |>
  filter(name=="Molokai_HI")|>
  ggplot(aes(x=date,y=tmax))+
  geom_line()+
  geom_point()
```

Density plot.

```{r}
ggplot(weather_df,aes(x=tmax,fill=name))+
  geom_density(alpha=0.3,adjust=.75)
```

Boxplots.

```{r}
ggplot(weather_df,aes(y=tmax,x=name))+
  geom_boxplot()
```

Violin plots.

```{r}
ggplot(weather_df,aes(y=tmax,x=name))+
  geom_violin()
```

Ridge plot.

```{r}
ggplot(weather_df,aes(x=tmax,y=name))+
  geom_density_ridges()
  geom_violin()
```

## saving and embedding plots

```{r}
ggp_weather=
  weather_df |>
  ggplot(aes(x=tmin,y=tmax))+
  geom_point()

ggsave("results/ggp_weather.pdf",ggp_weather)
```

```{r}
ggp_weather
```

## Same plot

Scales and colors and themes.

```{r}
weather_df |>
  #filter(tmax>=20, tmax<=30) |>
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point()+
  labs(title="Temperature Plot",
       x="Min daily temp (Degrees C)",
       y="Max daily temp",
       color="Location",
       caption="Max vs Min daily temp in three locations") +
  scale_x_continuous(breaks=c(-15,0,15),
                     labels=c("-15C","0C","15C")) +
  
  scale_y_continuous(position="right",
                     trans="sqrt") +
  viridis::scale_color_viridis(discrete=TRUE) +
  theme_classic() +
  theme(legend.position = "bottom")
```

## data argument

```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax))+
  geom_point()+
  geom_smooth()

nyc_weather_df = 
  weather_df |>
  filter(name == "CentralPark_NY")

hawaii_weather_df = 
  weather_df |>
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df, aes(x=date,y=tmax))+
  geom_point()+
  geom_line(data=hawaii_weather_df)
```

```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax,color=name))+
  geom_point()+
  facet_grid(.~name)
```

## Patchwork

```{r}
ggp_temp_scatter = 
  weather_df |>
  ggplot(aes(x=tmin,y=tmax,color=name)) +
  geom_point(alpha=.5)+
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |>
  filter(prcp>25) |>
  ggplot(aes(x=prcp, color=name))+
  geom_density(alpha=.5)+
  theme(legend.position = "none")

ggp_tmax_date = 
  weather_df |>
  ggplot(aes(x=date,y=tmax,color=name))+
  geom_point()+
  geom_smooth(se=FALSE)+
  theme(legend.position = "bottom")

(ggp_temp_scatter+ggp_prcp_density) / ggp_tmax_date
```

## Data manipulation

```{r}
weather_df |>
  mutate(name=fct_relevel(name,c("Molokai_HI","CentralPark_NY","Waterhole_WA"))) |>
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()

weather_df |>
  mutate(name=fct_reorder(name, tmax)) |>
  ggplot(aes(x=name,y=tmax,color=name)) +
  geom_violin()
```

## Complicte FAS plot

```{r}
litters_df =
  read.csv("data/FAS_litters.csv") |>
  janitor::clean_names() |>
  separate(group, into=c("dose","day_of_tx"),sep=3)

pups_df = 
  read.csv("data/FAS_pups.csv") |>
  janitor::clean_names()

fas_df = 
  left_join(pups_df, litters_df, by="litter_number")

fas_df |>
  select(dose,day_of_tx, starts_with("pd")) |>
  pivot_longer(pd_ears:pd_walk, names_to="outcome",values_to="pn_day") |>
  drop_na() |>
  mutate(outcome = fct_reorder(outcome, pn_day))|>
  ggplot(aes(x=dose,y=pn_day))+
  geom_violin()+
  facet_grid(day_of_tx~outcome)
```